import fs from "fs";
import path from "path";

/**
 * Standard bootstrap bridge (CLI-generated) — same resolution order as Vite entry inject.
 * @param {string} root
 */
export function resolveBootstrapBridge(root) {
  const candidates = [
    path.join(root, "src", "iui", "bootstrap.ts"),
    path.join(root, "src", "iui", "bootstrap.tsx"),
    path.join(root, ".iui", "generated", "bootstrap.generated.tsx"),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * Resolve standard user config paths for legacy compatibility shims.
 * @param {string} root
 * @param {string | null} [configPath]
 */
export function resolveBootstrapConfigPaths(root, configPath = null) {
  let themePath = configPath;
  if (!themePath) {
    for (const file of ["iui.config.ts", "iui.config.js", "iui.config.mjs"]) {
      const candidate = path.join(root, file);
      if (fs.existsSync(candidate)) {
        themePath = candidate;
        break;
      }
    }
  }

  const assetsCandidates = [
    path.join(root, "assets.config.json"),
    path.join(root, "assets.config.js"),
  ];
  const componentCandidates = [
    path.join(root, "component.config.ts"),
    path.join(root, "component.config.js"),
  ];

  const assetsPath = assetsCandidates.find((p) => fs.existsSync(p)) ?? null;
  const componentPath =
    componentCandidates.find((p) => fs.existsSync(p)) ?? null;

  return { themePath, assetsPath, componentPath };
}

/**
 * Inline bootstrap module using registerBootstrapState (unmigrated projects without CLI bridge).
 * @param {string} root
 * @param {string | null} [configPath]
 */
export function buildLegacyBootstrapShimSource(root, configPath = null) {
  const { themePath, assetsPath, componentPath } = resolveBootstrapConfigPaths(
    root,
    configPath,
  );

  if (!themePath) {
    return "export {};\n";
  }

  const lines = [
    "/** @deprecated Import src/iui/bootstrap or run iui doctor --fix */",
    `import theme from ${JSON.stringify(themePath)};`,
  ];

  if (assetsPath) {
    lines.push(`import assets from ${JSON.stringify(assetsPath)};`);
  }
  if (componentPath) {
    lines.push(
      `import { componentConfig as projectComponentConfig } from ${JSON.stringify(componentPath)};`,
    );
  }

  lines.push(
    'import { mergeProjectConfig, initFramework, registerBootstrapState } from "@inventive-ui/framework";',
    'import { initConfig as initSlotsConfig } from "@inventive-ui/framework/slots";',
    "",
    "const themeConfig = (theme)?.default ?? theme;",
  );

  if (assetsPath) {
    lines.push(
      "const frameworkConfig = mergeProjectConfig(themeConfig, assets);",
    );
  } else {
    lines.push("const frameworkConfig = themeConfig;");
  }

  lines.push(
    "registerBootstrapState({",
    "  frameworkConfig,",
    componentPath
      ? "  componentConfig: projectComponentConfig,"
      : "  componentConfig: undefined,",
    "});",
    "initFramework(frameworkConfig);",
    "initSlotsConfig(frameworkConfig);",
    "export {};",
    "",
  );

  return lines.join("\n");
}

/**
 * Disk/virtual shim: generated bootstrap bridge + compile manifest import.
 * @param {string} root
 * @param {{ includeManifest?: boolean, includeBuildHref?: boolean, includeInlineCss?: boolean, isServer?: boolean, publicCssReady?: boolean }} [options]
 */
export function buildBootstrapBridgeShimSource(root, options = {}) {
  const bootstrapBridge = resolveBootstrapBridge(root);
  if (!bootstrapBridge) {
    return buildLegacyBootstrapShimSource(root);
  }

  const buildManifest = path.join(root, ".iui", "cache", "manifest.js");
  const buildCssInline = path.join(root, ".iui", "cache", "styles.inline.js");
  const lines = [
    "/** Auto-generated by @inventive-ui/framework — do not edit */",
    `import ${JSON.stringify(bootstrapBridge)};`,
  ];

  if (options.includeManifest !== false) {
    lines.push(`import ${JSON.stringify(buildManifest)};`);
  }

  if (options.includeBuildHref) {
    lines.push(
      "const hash = globalThis.__IUI_BUILD__?.cssHash;",
      'if (hash) {',
      '  globalThis.__IUI_BUILD_CSS_HREF__ = "/iui/" + hash + ".css";',
      "}",
    );
  }

  if (
    options.includeInlineCss &&
    options.isServer &&
    !options.publicCssReady
  ) {
    lines.push(`import ${JSON.stringify(buildCssInline)};`);
  }

  lines.push("export {};", "");
  return lines.join("\n");
}

/**
 * @param {string} root
 */
export function isPublicIuiCssReady(root) {
  const buildManifest = path.join(root, ".iui", "cache", "manifest.js");
  try {
    if (!fs.existsSync(buildManifest)) return false;
    const publicDir = path.join(root, "public", "iui");
    if (!fs.existsSync(publicDir)) return false;
    return fs.readdirSync(publicDir).some((f) => f.endsWith(".css"));
  } catch {
    return false;
  }
}

/**
 * Webpack alias target for `iui-bootstrap`.
 * @param {string} root
 */
export function writeWebpackBootstrapShim(root) {
  const file = path.join(root, ".iui-bootstrap.js");
  const code = resolveBootstrapBridge(root)
    ? buildBootstrapBridgeShimSource(root, {
        includeManifest: true,
        includeBuildHref: false,
        includeInlineCss: false,
      })
    : buildLegacyBootstrapShimSource(root);
  fs.writeFileSync(file, code, "utf8");
  return file;
}
