import React from "react";
import { mapIllustrationSlotToPackageProps } from "./map-illustration-slot-props";
import { normalizeLoaderName } from "./normalize-loader-name";

type BoundComponent = React.ComponentType<Record<string, unknown>>;

const boundRegistry = new Map<string, Map<string, BoundComponent>>();

function normalizeLookupKey(slotType: string, key: string): string {
  if (slotType === "flag") {
    return key.toLowerCase().trim();
  }
  if (slotType === "loader") {
    return normalizeLoaderName(key);
  }
  return key;
}

function getBoundLookupKey(
  slotType: string,
  slot: Record<string, unknown>,
): string | null {
  switch (slotType) {
    case "icon":
    case "logo":
    case "color-logo":
      return typeof slot.name === "string" && slot.name.length > 0
        ? slot.name
        : null;
    case "flag":
      return typeof slot.code === "string" && slot.code.length > 0
        ? slot.code
        : null;
    case "file-type":
      return typeof slot.extension === "string" && slot.extension.length > 0
        ? slot.extension
        : null;
    case "loader":
      return typeof slot.name === "string" && slot.name.length > 0
        ? slot.name
        : null;
    case "illustration": {
      const name = slot.name;
      if (typeof name !== "string" || name.length === 0) {
        return null;
      }
      // Full Storyset ids: `{family}-{scene}-{hidden|simple|detailed}`
      const fullId = name.match(
        /^(amico|bro|cuate|pana|rafiki)-(.+)-(hidden|simple|detailed)$/i,
      );
      if (fullId) {
        return `${fullId[1].toLowerCase()}/${fullId[2]}`;
      }
      // Slot `style` is Storyset family (amico/bro/…), not CSS.
      const style = slot.style;
      const family =
        typeof style === "string" && style.length > 0
          ? style.toLowerCase()
          : "amico";
      return `${family}/${name}`;
    }
    default:
      return null;
  }
}

function stripSlotMeta(slot: Record<string, unknown>): Record<string, unknown> {
  const { type: _type, library: _library, ...rest } = slot;
  return rest;
}

/** Props passed into a bound glyph component for the given slot type. */
function toBoundComponentProps(
  slotType: string,
  slot: Record<string, unknown>,
): Record<string, unknown> {
  if (slotType === "illustration") {
    // Align with storyset.library.slot: never forward slot `style` (family
    // token) as React CSS `style`.
    return mapIllustrationSlotToPackageProps(slot, "bound");
  }
  return stripSlotMeta(slot);
}

/** Register statically imported asset components generated by the IUI CLI. */
export function registerBoundAssetComponents(
  slotType: string,
  components: Record<string, BoundComponent>,
): void {
  let map = boundRegistry.get(slotType);
  if (!map) {
    map = new Map();
    boundRegistry.set(slotType, map);
  }

  for (const [key, component] of Object.entries(components)) {
    if (!component) continue;
    map.set(normalizeLookupKey(slotType, key), component);
  }
}

/** Test-only / CLI regen helper. */
export function clearBoundAssetRegistry(): void {
  boundRegistry.clear();
}

/** Whether any bound glyphs are registered for a slot type (or any type when omitted). */
export function hasBoundAssets(slotType?: string): boolean {
  if (slotType) {
    const map = boundRegistry.get(slotType);
    return Boolean(map && map.size > 0);
  }
  let found = false;
  boundRegistry.forEach((map) => {
    if (map.size > 0) found = true;
  });
  return found;
}

/**
 * Re-render slots after warmup so lazy library wrappers and dynamic glyphs paint.
 * When bound glyphs are registered they already render synchronously, so a
 * warmup remount would throw away hydrated DOM (visible flash on reload).
 * Unbound catalog icons (e.g. pickers) still remount after prefetch.
 */
export function shouldUseSlotWarmupRemount(): boolean {
  return !hasBoundAssets();
}

/** Whether a bound glyph exists for this slot payload (registry non-empty). */
export function isBoundAssetRegistered(
  slotType: string,
  slot: Record<string, unknown>,
): boolean {
  const map = boundRegistry.get(slotType);
  if (!map || map.size === 0) {
    return false;
  }

  const lookupKey = getBoundLookupKey(slotType, slot);
  if (!lookupKey) {
    return false;
  }

  return map.has(normalizeLookupKey(slotType, lookupKey));
}

/**
 * Render a bound asset when the glyph is registered by `.iui/generated/assets`.
 * Returns `undefined` when the lazy Framework path should run.
 */
export function tryRenderBoundAsset(
  slotType: string,
  slot: Record<string, unknown>,
): React.ReactNode | undefined {
  const map = boundRegistry.get(slotType);
  if (!map || map.size === 0) {
    return undefined;
  }

  const lookupKey = getBoundLookupKey(slotType, slot);
  if (!lookupKey) {
    return undefined;
  }

  const Component = map.get(normalizeLookupKey(slotType, lookupKey));
  if (!Component) {
    return undefined;
  }

  return React.createElement(Component, toBoundComponentProps(slotType, slot));
}
