import React, { useSyncExternalStore } from "react";
import type { SlotEnvironment, SlotMap, SlotRendererFn } from "./slot-types";
import {
  getSlotWarmupEpoch,
  subscribeSlotWarmup,
} from "./warm-slot-assets";
import { shouldUseSlotWarmupRemount } from "./bound-asset-registry";

// Registry of slot renderers keyed by slot type.
// Uses SlotMap to keep renderers strictly typed.
const slotRenderers: Partial<{
  [K in keyof SlotMap]: SlotRendererFn<SlotMap[K], unknown>;
}> = {};

export function __resetSlotRegistryForTests() {
  for (const key of Object.keys(slotRenderers)) {
    delete slotRenderers[key as keyof typeof slotRenderers];
  }
}

function assignSlotRenderer<K extends keyof SlotMap>(
  type: K,
  renderer: SlotRendererFn<SlotMap[K], unknown>,
) {
  /**
   * Type assertion is intentional and safe.
   *
   * Reason:
   * - SlotMap is a discriminated union keyed by `slot.type`
   * - TypeScript cannot fully narrow generic unions at assignment time
   * - At runtime, `type` guarantees the correct slot shape
   *
   * This is a known TS limitation when mapping generics over unions.
   */
  slotRenderers[type] = renderer as Partial<{
    [Key in keyof SlotMap]: SlotRendererFn<SlotMap[Key], unknown>;
  }>[K];
}

// Register a renderer for a specific slot type.
export function registerSlot<K extends keyof SlotMap>(
  type: K,
  renderer: SlotRendererFn<SlotMap[K], unknown>,
) {
  if (slotRenderers[type]) {
    console.warn(`Slot "${String(type)}" already registered`);
  }

  assignSlotRenderer(type, renderer);
}

/**
 * Register CLI/codegen-produced slot renderers. Duplicate types are fatal
 * (compiler semantics) — plugin overrides use a separate API (Phase 4).
 */
export function registerGeneratedSlot<K extends keyof SlotMap>(
  type: K,
  renderer: SlotRendererFn<SlotMap[K], unknown>,
  source?: string,
) {
  if (slotRenderers[type]) {
    const lines = [
      `Duplicate generated slot registration: "${String(type)}"`,
      source ? `  Generated by: ${source}` : undefined,
    ].filter(Boolean);
    throw new Error(lines.join("\n"));
  }

  assignSlotRenderer(type, renderer);
}

// Central renderer that dispatches slots by their `type`.
export function SlotRenderer<K extends keyof SlotMap>({
  slot,
  env,
  children,
}: {
  slot: SlotMap[K];
  env?: SlotEnvironment<Partial<SlotMap[K]>>;
  children?: React.ReactNode;
}) {
  // Re-render after lazy slot warmup only when bound assets are not active.
  const warmupEpochRaw = useSyncExternalStore(
    subscribeSlotWarmup,
    getSlotWarmupEpoch,
    () => 0,
  );
  const useWarmupRemount = shouldUseSlotWarmupRemount();
  const warmupEpoch = useWarmupRemount ? warmupEpochRaw : 0;

  const renderer = slotRenderers[slot.type] as
    | SlotRendererFn<typeof slot, unknown>
    | undefined;

  if (!renderer) {
    console.warn(`[SlotRenderer] No renderer for slot type "${slot.type}"`);
    return null;
  }

  // Resolve slots that require preprocessing (icons, tokens, etc.)

  //removes resolvedSlot because defaults are different for each libraries
  // These defaults are sets by libraries itself
  // const resolvedSlot = slot.type === "icon" ? resolveIconSlot(slot) : slot;

  void warmupEpoch;

  const mergedFromEnv =
    env && typeof env.scope === "object" && env.scope !== null
      ? ({ ...env.scope, ...slot } as typeof slot)
      : slot;
  const effectiveEnv = env as SlotEnvironment<unknown> | undefined;
  const rendered = renderer(
    { children, ...mergedFromEnv } as typeof slot,
    effectiveEnv,
  );

  if (!useWarmupRemount) {
    return rendered;
  }

  return (
    <React.Fragment key={warmupEpoch}>{rendered}</React.Fragment>
  );
}