/**
 * @inventive-ui/framework/slots — slot registry, renderers, and asset warm-up.
 * Import this subpath when using SlotRenderer or registering slot libraries.
 */

// Registers all slot renderers via side effects (generated by npm run dev:update-slots)
import "./.generated/slot-registry";

export { useSlotRenderer } from "./hooks/use-slot-renderer";

export {
  SlotRenderer,
  registerSlot,
  registerGeneratedSlot,
} from "./utilities/slot/slot-registry";
export {
  registerBoundAssetComponents,
  tryRenderBoundAsset,
  hasBoundAssets,
  shouldUseSlotWarmupRemount,
} from "./utilities/slot/bound-asset-registry";

export type {
  Slot,
  SlotMap,
  SlotEnvironment,
  SlotRendererFn,
} from "./utilities/slot/slot-types";

export {
  registerIconLibrary,
  getIconLibraryRenderer,
} from "./utilities/slot/iconLibrary-registry";

export {
  registerIllustrationLibrary,
  getIllustrationLibraryRenderer,
} from "./utilities/slot/illustrationLibrary-registry";

export {
  registerFlagLibrary,
  getFlagLibraryRenderer,
} from "./utilities/slot/flagLibrary-registry";

export {
  registerFileTypeLibrary,
  getFileTypeLibraryRenderer,
} from "./utilities/slot/fileTypeLibrary-registry";

export {
  createEagerComponent,
  isReactComponentType,
  normalizeSlotModule,
  resolveComponentExport,
  prefetchOptionalModule,
  prefetchConfiguredSlotModules,
  prefetchConfiguredSlotModulesEager,
  loadOptionalModule,
} from "./utilities/slot/async-slot";
export {
  warmSlotAssets,
  resolveAssetPreloadTier,
} from "./utilities/slot/warm-slot-assets";
export type {
  ModuleLoader,
  OptionalSlotPackageId,
} from "./utilities/slot/async-slot";

/** Initialize config inside the slots bundle (separate from main `initFramework`). */
export { initConfig } from "./core/config-loader";
